import {
  IoHome,
  IoSearch,
  IoAdd,
  IoAddCircle,
  IoClose,
  IoCheckmarkCircle,
  IoWarning,
  IoPencil,
  IoRemove,
  IoTrash,
  IoCalendar,
} from "react-icons/io5";
import {
  FaUser,
  FaUserCircle,
  FaUserFriends,
  FaChartLine,
  FaParagraph,
  FaBold,
  FaUnderline,
  FaItalic,
  FaLink,
  FaHeart,
  FaRegHeart,
  FaRegEye,
} from "react-icons/fa";
import { LuLoaderCircle } from "react-icons/lu";

const I = {
  Add: IoAdd,
  AddCircle: IoAddCircle,
  Bold: FaBold,
  Calendar: IoCalendar,
  Chart: FaChartLine,
  Check: IoCheckmarkCircle,
  Close: IoClose,
  Eye: FaRegEye,
  Friends: FaUserFriends,
  Heart: FaHeart,
  HeartEmpty: FaRegHeart,
  Home: IoHome,
  Italic: FaItalic,
  Link: FaLink,
  Paragraph: FaParagraph,
  Pencil: IoPencil,
  Remove: IoRemove,
  Search: IoSearch,
  Spinner: LuLoaderCircle,
  Trash: IoTrash,
  Underline: FaUnderline,
  User: FaUser,
  UserCircle: FaUserCircle,
  Warning: IoWarning,
};

export { I };
